### ISSUE TITLE
NVIDIA EULA refers to the CUDA toolkit, not the CUDA samples

### ISSUE THREAD

**Issue by tvercaut** [luiscarlosgph/grabcut#1]
The EULA of the CUDA samples (version 7.0 which contained the grabcut sample code), is more permissive and should be included. See chapter 2 of:
http://developer.download.nvidia.com/compute/cuda/7_0/Prod/doc/EULA.pdf

In particular:
> **2.1.1. Source Code**
> Developer shall have the right to modify and create derivative works with the Source Code. Developer shall own any derivative works ("Derivatives") it creates to the Source Code, provided that Developer uses the Materials in accordance with the terms and conditions of this Agreement. Developer may distribute the Derivatives, provided that all NVIDIA copyright notices and trademarks are propagated and used properly and the Derivatives include the following statement: “This software contains source code provided by NVIDIA Corporation.

**Comment by luiscarlosgph** [comment]
The correct NVIDIA EULA is now attached to the code.
